name: Metrics
on:
  schedule: 
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ahmedmk11
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Cairo
          config_output: github-metrics.svg
