name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ahmedmk11
          
          template: isometric

          base: header, activity, community, repositories, metadata
          
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: detailed
          plugin_repositories: yes
          plugin_stars: yes
          plugin_followup: yes
          plugin_activity: yes
          plugin_activity_days: 14

          config_twemoji: no
          config_gemoji: no
          config_animations: no
          config_output: github-metrics.svg
